/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.facilita_uni.interfac;

import com.mycompany.facilita_uni.interfac.EletricidadeConta;
import com.mycompany.facilita_uni.interfac.FixaConta;
import com.mycompany.facilita_uni.interfac.InserirAtividade;
import com.mycompany.facilita_uni.interfac.ViewAtividades;
import com.mycompany.facilita_uni.interfac.ViewEletricidade;
import com.mycompany.facilita_uni.interfac.ViewFixa;
import com.mycompany.facilita_uni.interfac.AdicionarEletrodomestico;
import com.mycompany.facilita_uni.interfac.ViewEletrodomesticos;

/**
 *
 * @author Pedro
 */
public class BemVindo extends javax.swing.JFrame {

    /**
     * Creates new form BemVindo
     */
    public BemVindo() {
        initComponents();
        setLocationRelativeTo(null); // <-- centraliza a janela na tela
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inserir = new javax.swing.JMenu();
        inserirfixa = new javax.swing.JMenuItem();
        eletricidade = new javax.swing.JMenuItem();
        atividade = new javax.swing.JMenuItem();
        eletrodomestico = new javax.swing.JMenuItem();
        visualizar = new javax.swing.JMenu();
        viewFixas = new javax.swing.JMenuItem();
        viewLuz = new javax.swing.JMenuItem();
        viewAtividades = new javax.swing.JMenuItem();
        viewEletro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Bem vindo!");

        inserir.setText("Inserir");

        inserirfixa.setText("Fixa");
        inserirfixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirfixaActionPerformed(evt);
            }
        });
        inserir.add(inserirfixa);

        eletricidade.setText("Eletricidade");
        eletricidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletricidadeActionPerformed(evt);
            }
        });
        inserir.add(eletricidade);

        atividade.setText("Atividade");
        atividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadeActionPerformed(evt);
            }
        });
        inserir.add(atividade);

        eletrodomestico.setText("Eletrodoméstico");
        eletrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletrodomesticoActionPerformed(evt);
            }
        });
        inserir.add(eletrodomestico);

        jMenuBar1.add(inserir);

        visualizar.setText("Visualizar");

        viewFixas.setText("Contas Fixas");
        viewFixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFixasActionPerformed(evt);
            }
        });
        visualizar.add(viewFixas);

        viewLuz.setText("Contas de Luz");
        viewLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLuzActionPerformed(evt);
            }
        });
        visualizar.add(viewLuz);

        viewAtividades.setText("Atividades");
        viewAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAtividadesActionPerformed(evt);
            }
        });
        visualizar.add(viewAtividades);

        viewEletro.setText("Eletrodomésticos");
        viewEletro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEletroActionPerformed(evt);
            }
        });
        visualizar.add(viewEletro);

        jMenuBar1.add(visualizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eletricidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletricidadeActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EletricidadeConta().setVisible(true);
            }
        });
    }//GEN-LAST:event_eletricidadeActionPerformed

    private void inserirfixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirfixaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixaConta().setVisible(true);
            }
        });
    }//GEN-LAST:event_inserirfixaActionPerformed

    private void viewFixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFixasActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFixa().setVisible(true);
            }
        });
    }//GEN-LAST:event_viewFixasActionPerformed

    private void atividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadeActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirAtividade().setVisible(true);
            }
        });
    }//GEN-LAST:event_atividadeActionPerformed

    private void viewLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLuzActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEletricidade().setVisible(true);
            }
        });
    }//GEN-LAST:event_viewLuzActionPerformed

    private void viewAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAtividadesActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAtividades().setVisible(true);
            }
        });
    }//GEN-LAST:event_viewAtividadesActionPerformed

    private void eletrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletrodomesticoActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarEletrodomestico().setVisible(true);
            }
        });
    }//GEN-LAST:event_eletrodomesticoActionPerformed

    private void viewEletroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEletroActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEletrodomesticos().setVisible(true);
            }
        });
    }//GEN-LAST:event_viewEletroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BemVindo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem atividade;
    private javax.swing.JMenuItem eletricidade;
    private javax.swing.JMenuItem eletrodomestico;
    private javax.swing.JMenu inserir;
    private javax.swing.JMenuItem inserirfixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem viewAtividades;
    private javax.swing.JMenuItem viewEletro;
    private javax.swing.JMenuItem viewFixas;
    private javax.swing.JMenuItem viewLuz;
    private javax.swing.JMenu visualizar;
    // End of variables declaration//GEN-END:variables
}
