/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.facilita_uni.interfac;

// Imports necessários para integração com o sistema
import com.mycompany.facilita_uni.controle.Controlador;
import com.mycompany.facilita_uni.modelo.Atividade;
import com.mycompany.facilita_uni.modelo.Catalogo;
import com.mycompany.facilita_uni.persistencia.PersistenciaCatalogo;
/**
 *
 * @author Pedro
 */
public class InserirAtividade extends javax.swing.JFrame {

    /**
     * Creates new form InserirAtividade
     */
    public InserirAtividade() {
        initComponents();
        // Configurações adicionais da janela
        setTitle("Adicionar Atividade");
        setLocationRelativeTo(null); // Centralizar na tela
        setResizable(false); // Impedir redimensionamento
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        datatext = new javax.swing.JTextField();
        salvarFixa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nometext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Data");

        salvarFixa.setText("Salvar");
        salvarFixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarFixaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datatext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nometext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salvarFixa))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nometext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(salvarFixa)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarFixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarFixaActionPerformed
        // TODO add your handling code here:
 try {
            // Obter os dados dos campos de texto
            String nome = nometext.getText().trim();
            String data = datatext.getText().trim();
            
            // Validar se os campos não estão vazios
            if (nome.isEmpty() || data.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, preencha todos os campos!", 
                    "Campos Obrigatórios", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Validação básica do formato da data (ex: 05/05)
            if (!data.matches("\\d{2}/\\d{2}")) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, digite a data no formato DD/MM (ex: 05/05)!", 
                    "Formato de Data Inválido", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Carregar o controlador e catologo (mesmo processo do console e FixaConta)
            String caminhoArquivo = System.getProperty("user.dir") + "/dados.ser";
            PersistenciaCatalogo persistencia = new PersistenciaCatalogo();
            Controlador controlador = persistencia.carregarDeArquivo(caminhoArquivo);
            Catalogo catalogoAT = controlador.getCatalogo();
            
            // Criar e adicionar a nova atividade
            Atividade novaAtividade = new Atividade(nome, data);
            catalogoAT.adicionarAtividade(novaAtividade);
            
            // Salvar os dados no arquivo
            persistencia.salvarParaArquivo(controlador, caminhoArquivo);
            
            // Mostrar mensagem de sucesso
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Atividade adicionada com sucesso!\n" +
                "Nome: " + nome + "\n" +
                "Data: " + data, 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Limpar os campos após salvar
            limparCampos();
            
            // Opcional: fechar a janela após salvar
            // this.dispose();
            
        } catch (Exception e) {
            // Tratar qualquer erro inesperado
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao salvar a atividade: " + e.getMessage(), 
                "Erro", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_salvarFixaActionPerformed

    private void limparCampos() {
        nometext.setText("");
        datatext.setText("");
        nometext.requestFocus(); // Foca no primeiro campo
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datatext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nometext;
    private javax.swing.JButton salvarFixa;
    // End of variables declaration//GEN-END:variables
}
