/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.facilita_uni.interfac;

// Imports necessários para integração com o sistema
import com.mycompany.facilita_uni.controle.Controlador;
import com.mycompany.facilita_uni.modelo.ContasFixas;
import com.mycompany.facilita_uni.modelo.Usuario;
import com.mycompany.facilita_uni.persistencia.PersistenciaUsuario;

/**
 *
 * @author Pedro
 */
public class FixaConta extends javax.swing.JFrame {

   /**
     * Creates new form FixaConta
     */
    public FixaConta() {
        initComponents();
        // Configurações adicionais da janela
        setTitle("Adicionar Conta Fixa");
        setLocationRelativeTo(null); // Centralizar na tela
        setResizable(false); // Impedir redimensionamento
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datatext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valortext = new javax.swing.JTextField();
        salvarFixa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nometext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Valor");

        salvarFixa.setText("Salvar");
        salvarFixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarFixaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datatext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nometext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valortext, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salvarFixa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nometext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valortext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(salvarFixa)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void salvarFixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarFixaActionPerformed
        try {
            // Obter os dados dos campos de texto
            String nome = nometext.getText().trim();
            String data = datatext.getText().trim();
            String valorTexto = valortext.getText().trim();
            
            // Validar se os campos não estão vazios
            if (nome.isEmpty() || data.isEmpty() || valorTexto.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, preencha todos os campos!", 
                    "Campos Obrigatórios", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Converter o valor para inteiro
            int valor;
            try {
                valor = Integer.parseInt(valorTexto);
                if (valor <= 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "O valor deve ser um número positivo!", 
                        "Valor Inválido", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, digite um valor numérico válido!", 
                    "Formato Inválido", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Carregar o controlador e usuário (mesmo processo do console)
            String caminhoArquivo = System.getProperty("user.dir") + "/dados.ser";
            PersistenciaUsuario persistencia = new PersistenciaUsuario();
            Controlador controlador = persistencia.carregarDeArquivo(caminhoArquivo);
            Usuario usuario = controlador.getUsuario();
            
            // Criar e adicionar a nova conta fixa
            ContasFixas novaConta = new ContasFixas(valor, nome, data);
            usuario.adicionarContaFixa(novaConta);
            
            // Salvar os dados no arquivo
            persistencia.salvarParaArquivo(controlador, caminhoArquivo);
            
            // Mostrar mensagem de sucesso
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Conta fixa adicionada com sucesso!\n" +
                "Nome: " + nome + "\n" +
                "Valor: R$ " + valor + "\n" +
                "Vencimento: " + data, 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Limpar os campos após salvar
            limparCampos();
            
            // Opcional: fechar a janela após salvar
            // this.dispose();
            
        } catch (Exception e) {
            // Tratar qualquer erro inesperado
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao salvar a conta: " + e.getMessage(), 
                "Erro", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_salvarFixaActionPerformed

    
       private void limparCampos() {
        nometext.setText("");
        datatext.setText("");
        valortext.setText("");
        nometext.requestFocus(); // Foca no primeiro campo
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datatext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nometext;
    private javax.swing.JButton salvarFixa;
    private javax.swing.JTextField valortext;
    // End of variables declaration//GEN-END:variables
}
